apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: etapau/hello-world
          imagePullPolicy: Always
          name: hello-world
          ports:
            - containerPort: 9000
              protocol: TCP
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
