---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
  labels:
    app: hello-world
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: hello-world
