apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yml

patchesStrategicMerge:
  - deploy.yml

namePrefix: dev-
namespace: dev
replicas:
  - name: hello-world
    count: 2
