apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.5/manifests/install.yaml
  - project-dev.yml
  - project-prod.yml
  - apps/hello-world
  - app-argocd.yml
