apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          livenessProbe:
            httpGet:
              port: 9000
              path: /healthz
            initialDelaySeconds: 2
            periodSeconds: 2
